// Register the service worker generated by vite-plugin-pwa. We skip
// registration inside the Lovable preview iframe to avoid serving a
// stale cached shell in the editor preview.
import { registerSW } from "virtual:pwa-register";

export type PwaStatus = "idle" | "ready" | "updated" | "offline-ready";
type Listener = (status: PwaStatus) => void;

let updateSW: ((reload?: boolean) => Promise<void>) | null = null;
let lastStatus: PwaStatus = "idle";
const listeners = new Set<Listener>();

function emit(status: PwaStatus) {
  lastStatus = status;
  listeners.forEach((cb) => cb(status));
}

function isPreviewContext(): boolean {
  if (typeof window === "undefined") return true;
  try {
    if (window.self !== window.top) return true;
  } catch {
    return true;
  }
  const host = window.location.hostname;
  return host.includes("lovableproject.com") || host.includes("lovable.app") || host.includes("id-preview--");
}

export function initPwa() {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
  if (isPreviewContext()) {
    // Clean up any previously-registered SWs inside the preview iframe.
    navigator.serviceWorker.getRegistrations().then((regs) => regs.forEach((r) => r.unregister())).catch(() => {});
    return;
  }
  try {
    updateSW = registerSW({
      immediate: true,
      onNeedRefresh() { emit("updated"); },
      onOfflineReady() { emit("offline-ready"); },
      onRegistered() { emit("ready"); },
      onRegisterError(err) { console.warn("[pwa] register error", err); },
    });
  } catch (err) {
    console.warn("[pwa] init failed", err);
  }
}

export function applyPendingUpdate() {
  if (updateSW) void updateSW(true);
  else if (typeof window !== "undefined") window.location.reload();
}

export function subscribePwa(listener: Listener) {
  listeners.add(listener);
  if (lastStatus !== "idle") listener(lastStatus);
  return () => { listeners.delete(listener); };
}